### ISSUE TITLE
sendText crashes when dns lookup fails

### ISSUE THREAD

**Issue by henridf** [shz/node-mailgun#23]
The node process crashes on an uncaught error when calling `sendText` when the network is disconnected:

```
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: getaddrinfo ENOTFOUND api.mailgun.net api.mailgun.net:443
    at errnoException (dns.js:26:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:77:26)
```

This is due to the lack of error handler on the https request object. Adding a handler like:

```
req.on('error', function(e) {
...
});
```
on the request object fixes the issue.

**Comment by paps** [comment]
I was also affected by this, yesterday. Can you merge #25? Thanks

**Comment by paps** [comment]
Hey @shz, do you even read these?
